ALTER TABLE cash_payments
ADD COLUMN `amount` DECIMAL(10,2) DEFAULT NULL,
ADD COLUMN `paid_to` VARCHAR(55) DEFAULT NULL,
ADD COLUMN `dname` VARCHAR(255) DEFAULT NULL,
ADD COLUMN `dnum` BIGINT(20) DEFAULT NULL,
ADD COLUMN `pdate` datetime DEFAULT NULL,
ADD COLUMN `note` TEXT DEFAULT NULL,;
